### ISSUE TITLE
Private Members

### ISSUE THREAD

**Issue by SephLeague** [EsotericSoftware/reflectasm#47]
Why can private members not be accessed? Aren't you just adding a getter as java bytecode using ASM?

**Comment by NathanSweet** [comment]
No, it isn't adding a getter to an existing class, it's creating a new class with the bytecodes to access the field. You can use default access fields, which can work because it tries to create the new class in the same package. If not, the JVM enforces no access to private fields through bytecode. You can use reflection with `setAccessible(true)`.

**Comment by hepin1989** [comment]
So we could only access it when it is public ,or  ddefault?Thanks

**Comment by hepin1989** [comment]
So we could only access it when it is public ,or  ddefault?Thanks

**Comment by NathanSweet** [comment]
Yes.
