### ISSUE TITLE
Repackage asm 

### ISSUE THREAD

**Issue by greenlaw110** [EsotericSoftware/reflectasm#54]
This library use asm 5.1 (at the moment) direclty. However as per http://asm.ow2.org/doc/faq.html#Q15, it suggest that 

> Tools and frameworks that are using ASM for bytecode processing (e.g. Hibernate, CGLIB, AspectWerkz) should repackage ASM code within their own name space. This can be automated with Jar Jar Links tool.

Here is a [real issue](https://github.com/actframework/actframework/issues/85) caused by ASM library version conflict between sun's jersey and ReflectASM

**Comment by NathanSweet** [comment]
I tried, jar jar links appears to be [broken](https://github.com/shevek/jarjar/issues/8).

**Comment by greenlaw110** [comment]
@NathanSweet 

Well IDE is your friend, it's very simple to load all ASM code into your ide and run a code refactory to change the package name. You don't really need jarjar to work.

**Comment by NathanSweet** [comment]
I'd rather modify the built artifact provided by ObjectWeb than repackage it from source each time it needs updating. As you can see in the jarjar issue, I got it to work. Their docs were outdated and their launcher code half wrong.

**Comment by greenlaw110** [comment]
My approach is to create a [separate project](https://github.com/actframework/act-asm) that package the asm, and maintain that project including release it as a separate jar in the maven repository.

But anyway it's your call

**Comment by magro** [comment]
@NathanSweet I guess pom.xml still has to be adjusted to make this work for other users and in the context of releasing to maven, right?!

**Comment by NathanSweet** [comment]
@magro Yes.

**Comment by magro** [comment]
We're already building/releasing a shaded jar, creating an additional artifact with a classifier attached. We could use the shading approach and just release the shaded jar instead of using jarjar (not sure how this would be integrated via maven).

**Comment by NathanSweet** [comment]
Normally I would leave shading to whoever is cobbling together conflicting dependencies, but if the ASM people are saying we should shade their lib and distribute that, then I guess we don't need a non-shaded JAR.

Maven doesn't have to use jar jar, though it's possible. Can we shade it to "com.esotericsoftware.asm"?

Is it a problem for Maven that I use a shaded ASM JAR as a dependency? That means the ReflectASM source is using shaded imports.

**Comment by magro** [comment]
> Can we shade it to "com.esotericsoftware.asm"?

Yes we can. In the PR (#57) I left it unchanged to keep changes as small as possible, but I don't think that changing to "com.esotericsoftware.asm" would break anything (assuming nobody uses the shaded classes of course). What's your motivation btw? 

> Is it a problem for Maven that I use a shaded ASM JAR as a dependency? That means the ReflectASM source is using shaded imports.

That's the problem, because maven doesn't use the patched asm jar, but the original one as declared as dependency. Therefore compilation fails.

**Comment by NathanSweet** [comment]
The long package name was just very long. :)

I'm fine with shading it after building the ReflectASM JAR. Next time I want to do a release for GitHub I'll probably make scar/jarjar do it.

**Comment by magro** [comment]
> Next time I want to do a release for GitHub I'll probably make scar/jarjar do it.

So you're not going to use `mvn package` for this? Shall we set up the maven/sonatype push-to-maven-central stuff for you? It's not that much...

**Comment by hepin1989** [comment]
```
Caused by: java.lang.NoSuchMethodError: org.objectweb.asm.ClassWriter.<init>(I)V
  at com.esotericsoftware.reflectasm.MethodAccess.get(MethodAccess.java:120)
  at com.taobao.xgraphql.annotation.AnnotationToAST.getGraphQLObjectType(AnnotationToAST.java:451)
```
the packed version is not released,so ....

**Comment by hepin1989** [comment]
I have done a shade in my local code:)

**Comment by NathanSweet** [comment]
> So you're not going to use mvn package for this?

@magro Since I'm not a Maven user, doing releases that way is asking for trouble. If it's OK with you, you can be the Maven master.

Does anything more need to be done for this isssue? Currently the ReflectASM source is using an ASM JAR repacked to com.esotericsoftware.asm. We need a new 1.11.6 Maven release (#60), so once that is done I think we can close this.

**Comment by magro** [comment]
@NathanSweet Your commit ade0542 broke the build, i.e. right now it's not possible anymore for me to publish the library. I don't have the time to check out other ways of building / publishing. If you want me to publish this thing to maven central so that kryo can use a new version I see nothing else than reverting the mentioned commit and merge #57 instead (of course there we can change the package name to `com.esotericsoftware.asm`).

**Comment by NathanSweet** [comment]
Yep, reverting and doing the repack with Maven is fine.
